# Generated by Django 6.0.5 on 2026-07-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_bulkinquiry_subscriptionplan_product_aroma_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmtrackingstep',
            name='step',
            field=models.CharField(choices=[('farm_selected', 'Farm Selected'), ('harvested', 'Harvested'), ('cleaned', 'Cleaned'), ('quality_checked', 'Quality Checked'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('return_requested', 'Return Requested')], max_length=50),
        ),
    ]
