# Generated by Django 6.0.5 on 2026-07-29 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_customer_profile_address_buylater'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('quality_issue', 'Quality issue'), ('damaged_pack', 'Damaged pack'), ('wrong_item', 'Wrong item'), ('late_delivery', 'Late delivery'), ('changed_mind', 'Changed mind'), ('other', 'Other')], max_length=40)),
                ('pickup_address', models.TextField()),
                ('refund_mode', models.CharField(choices=[('original', 'Original payment method'), ('wallet', 'Store wallet'), ('replacement', 'Replacement product'), ('bank', 'Bank transfer')], default='original', max_length=30)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='returns/')),
                ('note', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='requested', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='return_request', to='store.order')),
            ],
        ),
    ]
